version: '2'

services:
  mongo-db:
    image: mongo:latest
    restart: always
    networks:
      - backend
    ports:
      - 27017:27017
    # volumes:
    #   - "./mongo-data:/data/db"

  server:
    build: 
     context: ./
    container_name: express-typescript-api
    command: bash -c 'while !</dev/tcp/mongo-db/27017; do sleep 1; done; npm start'
    restart: always
    ports:
      - 7000:7000
    # volumes:
    #   - "./logs:/usr/src/server/logs"
    env_file:
      - example.env
    environment:
      - DB_HOST=mongo-db
    networks:
      - backend
    depends_on:
      - mongo-db

networks:
  backend:
    driver: bridge